name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install ldid
        run: |
          curl -sLo $HOME/ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus5/ldid_macos_x86_64
          chmod +x $HOME/ldid
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Compile
        run: make all -C checkra1n/Kernel16Patcher
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: KPF
          path: |
            checkra1n/Kernel16Patcher/Kernel16Patcher.ios
            checkra1n/Kernel16Patcher/Kernel16Patcher-nolivefs.ios
