name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Voodoo magic
        id: voodoo
        uses: actions/cache@v2
        with:
          key: ${{ github.event_name }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            push-${{ github.ref }}-
            push-
          path: |
            **
      - name: Install ldid
        run: |
          sudo curl -sLO /usr/bin/ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus5/ldid_macos_x86_64
      - name: Checkout repository
        if: steps.voodoo.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update repository
        if: steps.voodoo.outputs.cache-hit == 'true'
        run: |
          git fetch --all
          git reset --hard origin/$(git branch --show-current)
          git submodule update --recursive --remote
      - name: Compile
        run: make all -C checkra1n/Kernel16Patcher
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: KPF
          path: |
            checkra1n/Kernel16Patcher/Kernel16Patcher.ios
            checkra1n/Kernel16Patcher/Kernel16Patcher-nolivefs.ios
